# This rule is not used by the project fluxup itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to fluxup.fluxup.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fluxup
    app.kubernetes.io/managed-by: kustomize
  name: managedapp-viewer-role
rules:
- apiGroups:
  - fluxup.fluxup.dev
  resources:
  - managedapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fluxup.fluxup.dev
  resources:
  - managedapps/status
  verbs:
  - get
